const ALL_PRODUCTS = 'ALL_PRODUCTS';
const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';

const PRODUCT_BY_ID = 'PRODUCT_BY_ID';
const PRODUCT_BY_ID_SUCCESS = 'PRODUCT_BY_ID_SUCCESS';

const ADD_PRODUCT = 'ADD_PRODUCT';
const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';

const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';

const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';

const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_FROM_CART = 'REMOVE_FROM_CART';

const ALL_MANUFACTURERS = 'ALL_MANUFACTURER';
const ALL_MANUFACTURERS_SUCCESS = 'ALL_MANUFACTURER_SUCCESS';

const ERROR_MSG = 'ERROR_MSG';

export {
    ALL_PRODUCTS,
    ADD_PRODUCT_SUCCESS,
    PRODUCT_BY_ID,
    PRODUCT_BY_ID_SUCCESS,
    ALL_PRODUCTS_SUCCESS,
    ADD_PRODUCT,
    UPDATE_PRODUCT,
    UPDATE_PRODUCT_SUCCESS,
    REMOVE_PRODUCT,
    REMOVE_PRODUCT_SUCCESS,
    ADD_TO_CART,
    REMOVE_FROM_CART,
    ALL_MANUFACTURERS,
    ALL_MANUFACTURERS_SUCCESS,
    ERROR_MSG,
};
